name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 build:
 runs-on: ubuntu-latest
    name: generate

    steps:
 - uses: actions/checkout@v2
 - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
 USERNAME: ${{ github.repository_owner }}
